### ISSUE TITLE
Kibana pod fails to start

### ISSUE THREAD

**Issue by jbunce** [floragunncom/search-guard-helm#6]
Kibana fails to start with the following log message:

```
{"type":"log","@timestamp":"2019-02-05T04:57:35Z","tags":["info","optimize"],"pid":1,"mes
sage":"Optimizing and caching bundles for stateSessionStorageRedirect, status_page, timel
ion, monitoring, dashboardViewer, canvas, infra, searchguard-login, searchguard-customerr
or, searchguard-multitenancy, searchguard-accountinfo, searchguard-configuration and kiba
na. This may take a few minutes"}
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite
browserslist`
{"type":"error","@timestamp":"2019-02-05T05:03:13Z","tags":["connection","client","error"
],"pid":1,"level":"error","error":{"message":"socket hang up","name":"Error","stack":"Err
or: socket hang up\n    at TLSSocket.<anonymous> (_tls_wrap.js:890:25)\n    at emitOne (e
vents.js:121:20)\n    at TLSSocket.emit (events.js:211:7)\n    at _handle.close (net.js:5
61:12)\n    at Socket.done (_tls_wrap.js:360:7)\n    at Object.onceWrapper (events.js:315
:30)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at TCP
._handle.close [as _onclose] (net.js:561:12)","code":"ECONNRESET"},"message":"socket hang
 up"}
```

**Comment by jbunce** [comment]
It took 17 minutes but eventually Kibana comes up

**Comment by jbunce** [comment]
Once the Kibana pod is up it's inaccessible:

```
PORT     STATE SERVICE
5601/tcp open  esmagent

Nmap done: 1 IP address (1 host up) scanned in 0.26 seconds
```

```
curl <host>:5601           
curl: (52) Empty reply from server
```

**Comment by floragunncom** [comment]
Can you try `curl -k https://<host>:5601`

**Comment by scottwallred** [comment]
Did you ever get it working.  Seeing the same issues running on GKE

Thanks.

**Comment by anandgavai** [comment]
The problem appears to be be in kibana.yml file in the config directory as https connection for elasticsearch is not enabled. Wonder if is possible to fix it within this image itself without having to configure kibana.yml file explicitly.
